[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
optimizer = true
optimizer_runs = 80
fs_permissions = [{ access = "read-write", path = "./deploy"}]
# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[etherscan]
arbitrum-goerli = { key = "add key"}