name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Run Forge Fmt Check
        run: |
          forge fmt --check
        id: fmt_check

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes
        id: build

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test

      - name: Run Code Coverage
        run: |
          forge coverage --report lcov
        id: coverage

      - name: Generate Coverage Report
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: ./lcov.info
          minimum-coverage: 70
          artifact-name: code-coverage-report
          github-token: ${{ secrets.GITHUB_TOKEN }}
